
import { GoogleGenAI } from "@google/genai";

const API_KEY = process.env.API_KEY;

if (!API_KEY) {
    throw new Error("API_KEY is not defined in environment variables");
}

const ai = new GoogleGenAI({ apiKey: API_KEY });

export const generateLyrics = async (idea: string, style: string, title: string): Promise<string> => {
    const prompt = `
Eres un compositor de canciones experto y poeta. Tu misión es crear la letra para una canción original, completa y emotiva basada en la siguiente idea y estilo musical.

La estructura de la canción debe ser clara y profesional, incluyendo secciones como [Verso 1], [Coro], [Verso 2], [Puente], y [Outro]. Si la idea es muy simple, puedes añadir un segundo puente o repetir el coro.

Adapta el tono, el lenguaje y la estructura de la letra para que coincida con el estilo musical especificado. Por ejemplo, una canción de rock podría tener un lenguaje más directo y enérgico, mientras que una balada sería más introspectiva y suave.

Por favor, asegúrate de que la letra sea creativa, poética y que capture la esencia de la idea proporcionada por el usuario. Responde únicamente con la letra de la canción.

${title.trim() ? `**Título de la canción:**\n"${title}"\n` : ''}
**Idea del usuario:**
"${idea}"

**Estilo musical:**
"${style}"

**Letra de la canción generada:**
`;

    try {
        const response = await ai.models.generateContent({
            model: 'gemini-2.5-flash',
            contents: prompt,
        });

        if (response && response.text) {
            return response.text;
        } else {
            throw new Error("No text was generated by the API.");
        }
    } catch (error) {
        console.error("Error calling Gemini API:", error);
        throw new Error("Failed to generate lyrics from Gemini API.");
    }
};

export const improveLyrics = async (currentLyrics: string, style: string, title: string): Promise<string> => {
    const prompt = `
Eres un letrista y editor musical de clase mundial. Tu tarea es tomar la siguiente letra de canción y mejorarla significativamente.
Enfócate en hacerla más poética, vívida y emocionalmente resonante. Refina las metáforas, fortalece las imágenes y asegura un flujo lírico suave y profesional.
No cambies el tema central, el significado o la estructura de la canción (por ejemplo, mantén los [Verso], [Coro], etc.). Tu objetivo es elevar el lenguaje y el arte de la letra existente.

Responde únicamente con la letra completa y mejorada.

${title.trim() ? `**Título de la canción (para contexto):**\n"${title}"\n` : ''}
**Estilo musical (para contexto):**
"${style}"

**Letra de la canción a mejorar:**
---
${currentLyrics}
---

**Letra de la canción mejorada:**
`;

    try {
        const response = await ai.models.generateContent({
            model: 'gemini-2.5-flash',
            contents: prompt,
        });
        
        if (response && response.text) {
            return response.text;
        } else {
            throw new Error("No improved text was generated by the API.");
        }
    } catch (error) {
        console.error("Error calling Gemini API for improvement:", error);
        throw new Error("Failed to improve lyrics from Gemini API.");
    }
};
