
import { GoogleGenAI } from "@google/genai";

const API_KEY = process.env.API_KEY;

if (!API_KEY) {
    throw new Error("API_KEY is not defined in environment variables");
}

const ai = new GoogleGenAI({ apiKey: API_KEY });

export const generateLyrics = async (idea: string): Promise<string> => {
    const prompt = `
Eres un compositor de canciones experto y poeta. Tu misión es crear la letra para una canción original, completa y emotiva basada en la siguiente idea.

La estructura de la canción debe ser clara y profesional, incluyendo secciones como [Verso 1], [Coro], [Verso 2], [Puente], y [Outro]. Si la idea es muy simple, puedes añadir un segundo puente o repetir el coro.

Por favor, asegúrate de que la letra sea creativa, poética y que capture la esencia de la idea proporcionada por el usuario. Responde únicamente con la letra de la canción.

**Idea del usuario:**
"${idea}"

**Letra de la canción generada:**
`;

    try {
        const response = await ai.models.generateContent({
            model: 'gemini-2.5-flash',
            contents: prompt,
        });

        if (response && response.text) {
            return response.text;
        } else {
            throw new Error("No text was generated by the API.");
        }
    } catch (error) {
        console.error("Error calling Gemini API:", error);
        throw new Error("Failed to generate lyrics from Gemini API.");
    }
};
